name: hello-world
on: push 
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World! second"
      - uses: brpaz/hadolint-action@v1.2.1
         with:
           dockerfile: ./Dockerfile
